dist: xenial
language: python
cache: pip
install: pip install --upgrade tox
script: tox

# Drop once EOL: https://devguide.python.org/#status-of-python-branches
# Also bump python_requires in setup.py
jobs:
  include:
    ## Linux

    # CPython (in official virtualenv)
    - python: '2.7'
    - python: '3.5'
    - python: '3.6'
    - python: '3.7'
    - python: '3.8'  # pytype is currently <= 3.8
      env: TOXENV=doctest,black,pylint,pytype,bandit,coverage
    - python: '3.9'

    # PyPy (in official virtualenv)
    - python: pypy
      env: TOXENV=pypy
    - python: pypy3
      env: TOXENV=pypy3

    ## OSX

    # CPython (in virtualenv, since it's not officially supported)
    - os: osx
      language: sh
      env:
        - TOXENV=py3  # Whatever one you happen to get...
        - HOMEBREW_NO_INSTALL_CLEANUP=1
        - HOMEBREW_NO_ANALYTICS=1
      before_cache:
        - rm -f "$HOME/Library/Caches/pip/log/debug.log"
      cache:
        directories:
          - "$HOME/Library/Caches/pip"
      addons:
        homebrew:
          packages: python3
      before_install:
        - python3 -m pip install --upgrade virtualenv
        - virtualenv -p python3 "$HOME/venv"
        - source "$HOME/venv/bin/activate"

      ## Windows

    - os: windows
      language: shell
      env:
        - TOXENV=py39
      before_install:
        - choco install python --version 3.8.1
        - python --version
        - python -m pip install --upgrade pip
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH

    ## Special jobs

    # Run long Hypothesis tests for release/cron
    - if: branch =~ ^release/.*$ or type = cron
      python: '3.8'
      env: TOXENV=py-release

notifications:
  email:
    - travis+srt@chrisdown.name
